# Generated by Django 3.2 on 2025-12-07 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251205_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким юзернеймом уже существует.'}, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message=('Юзернейм может содержать только буквы', 'цифры и символы: @.+-'), regex='^[w.@+-]+Z')], verbose_name='Уникальный юзернейм'),
        ),
    ]
